version: 0.2

phases:
  install:
    commands:
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH="$HOME/.local/bin:$PATH"
      - poetry install --with dev
  build:
    commands:
      - pytest
